version: '3.4'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - '${PORT_ZOOKEEPER:-2181}:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
      - zookeeper-secrets:/etc/zookeeper/secrets
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'WARN'

  broker1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - '${PORT_BROKER1:-29092}:29092'
    volumes:
      - broker1-data:/var/lib/kafka/data
      - broker1-secrets:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INTERNAL://broker1:9092,EXTERNAL://broker1:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker1:9092,EXTERNAL://localhost:${PORT_BROKER1:-29092}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: '60000'  # check whether to delete log segments ever minute (default 5 minutes)
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_LOG4J_LOGGERS: "\
        kafka=WARN,\
        kafka.controller=WARN,\
        kafka.log.LogCleaner=WARN,\
        state.change.logger=WARN,\
        kafka.producer.async.DefaultEventHandler=WARN"

  ai-consumer:
    build: ./services/ai-consumer
    container_name: ai-consumer
    depends_on:
      - broker1
    environment:
      - KAFKA_BOOTSTRAP=broker1:9092
      - GROUP_ID=ai-consumer
      - INPUT_TOPIC=transactions
      - PREDICTIONS_TOPIC=predictions

  disputes-api:
    build: ./services/disputes-api
    container_name: disputes-api
    volumes:
      - disputes-data:/data
    ports:
      - "8000:8000"

  


volumes:
  zookeeper-data:
  zookeeper-logs:
  zookeeper-secrets:
  broker1-data:
  broker1-secrets:
  connect-plugins:
  disputes-data:
  # note: technically it's not required to define and mount the above volumes, but in that
  # case Docker Compose will create anonymous volumes with unreadable identifiers, and it
  # will not be much clear what container is using what volume (unless using docker inspect)
